version: '3'

services:
    web: 
        build: . 
        command: python /app/django_course_site/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/"]
            interval: 1m
            timeout: 10s
            retries: 3